[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --alluredir=allure-results

# Silencia avisos de bibliotecas de terceiros que não dependem de nós
filterwarnings =
    ignore::DeprecationWarning:websockets.*
    ignore::DeprecationWarning:uvicorn.*
    ignore::DeprecationWarning:httpx.*
